[doc quick]

diff --git a/.github/workflows/build_docs.yml b/.github/workflows/build_docs.yml
--- a/.github/workflows/build_docs.yml
+++ b/.github/workflows/build_docs.yml
@@ -68,3 +68,89 @@ jobs:
           directory: hidimstat
           github_token: ${{ secrets.GITHUB_TOKEN }}
           
+  get_artifact:
+    name: Deploy documentation  
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install jq
+        run: sudo apt-get install -y jq
+
+      - name: Wait for CircleCI Job to Complete
+        id: wait_for_circleci
+        run: |
+          CIRCLECI_TOKEN=${{ secrets.CIRCLECI_TOKEN }}
+          CIRCLECI_PROJECT_SLUG="gh/lionelkusch/hidimstat"  # Replace with your CircleCI project slug
+          CIRCLECI_BUILD_NUM=$(curl -s -H "Circle-Token: $CIRCLECI_TOKEN" "https://circleci.com/api/v2/project/$CIRCLECI_PROJECT_SLUG/pipeline" | jq -r '.items[0].number')
+
+          # Poll the job status until it completes
+          while true; do
+            JOB_STATUS=$(curl -s -H "Circle-Token: $CIRCLECI_TOKEN" "https://circleci.com/api/v2/project/$CIRCLECI_PROJECT_SLUG/pipeline/$CIRCLECI_BUILD_NUM" | jq -r '.state')
+            if [[ "$JOB_STATUS" == "completed" ]]; then
+              echo "CircleCI job completed successfully."
+              break
+            elif [[ "$JOB_STATUS" == "failed" ]]; then
+              echo "CircleCI job failed."
+              exit 1
+            else
+              echo "CircleCI job is still running. Waiting..."
+              sleep 30
+            fi
+          done
+
+      - name: Get CircleCI Artifact URL
+        id: get_artifact_url
+        run: |
+          CIRCLECI_TOKEN=${{ secrets.CIRCLECI_TOKEN }}
+          CIRCLECI_PROJECT_SLUG="gh/lionelkusch/hidimstat"  
+          CIRCLECI_BUILD_NUM=$(curl -s -H "Circle-Token: $CIRCLECI_TOKEN" "https://circleci.com/api/v2/project/$CIRCLECI_PROJECT_SLUG/pipeline" | jq -r '.items[0].number')
+          ARTIFACT_URL=$(curl -s -H "Circle-Token: $CIRCLECI_TOKEN" "https://circleci.com/api/v2/project/$CIRCLECI_PROJECT_SLUG/$CIRCLECI_BUILD_NUM/artifacts" | jq -r '.items[0].url')
+          echo "::set-output name=artifact_url::$ARTIFACT_URL"
+
+      - name: Download Artifact
+        run: |
+          ARTIFACT_URL=${{ steps.get_artifact_url.outputs.artifact_url }}
+          curl -L -o artifact.zip "$ARTIFACT_URL"
+          unzip artifact.zip -d ./artifact
+
+      - name: List Artifact Contents
+        run: ls -R ./artifact
+
+      - name: Upload Artifact to GitHub
+        uses: actions/upload-artifact@v3
+        with:
+          name: circleci-artifact
+          path: ./artifact
+  
+  
+  deploy_documentation:
+    name: Deploy documentation  
+    runs-on: ubuntu-latest
+    needs: [get_artifact]
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Add SSH key
+        env:
+          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
+        run: |
+          mkdir -p ~/.ssh
+          ssh-keyscan github.com >> ~/.ssh/known_hosts
+          echo "${{ secrets.ACTIONS_SSH_DEPLOY }}" > ~/.ssh/github_actions
+          chmod 600 ~/.ssh/github_actions
+          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
+          ssh-add ~/.ssh/github_actions
+
+      - uses: actions/download-artifact@v4
+        with:
+          name: circleci-artifact
+          path: ./html
+
+      - name: deploy
+        env:
+          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
+          COMMIT_SHA: ${{ github.event.head_commit.id }}
+        run: |
+          git config --global user.email "actions@github.com"
+          git config --global user.name "GitHub actions"
+          ./build_tools/circle/push_doc.sh
